apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: huggingface-albert
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=albert
        - --model_id=albert/albert-base-v2
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
